/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestRouteImport } from './routes/request'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GarageDispatchRouteImport } from './routes/garage-dispatch'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GarageDispatchServicesRouteImport } from './routes/garage-dispatch.services'
import { Route as GarageDispatchReviewsRouteImport } from './routes/garage-dispatch.reviews'
import { Route as GarageDispatchNewsRouteImport } from './routes/garage-dispatch.news'
import { Route as GarageDispatchLoginRouteImport } from './routes/garage-dispatch.login'
import { Route as GarageDispatchGalleryRouteImport } from './routes/garage-dispatch.gallery'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageDispatchRoute = GarageDispatchRouteImport.update({
  id: '/garage-dispatch',
  path: '/garage-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const GarageDispatchServicesRoute = GarageDispatchServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => GarageDispatchRoute,
} as any)
const GarageDispatchReviewsRoute = GarageDispatchReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => GarageDispatchRoute,
} as any)
const GarageDispatchNewsRoute = GarageDispatchNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => GarageDispatchRoute,
} as any)
const GarageDispatchLoginRoute = GarageDispatchLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GarageDispatchRoute,
} as any)
const GarageDispatchGalleryRoute = GarageDispatchGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => GarageDispatchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRoute
  '/gallery': typeof GalleryRoute
  '/garage-dispatch': typeof GarageDispatchRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/garage-dispatch/gallery': typeof GarageDispatchGalleryRoute
  '/garage-dispatch/login': typeof GarageDispatchLoginRoute
  '/garage-dispatch/news': typeof GarageDispatchNewsRoute
  '/garage-dispatch/reviews': typeof GarageDispatchReviewsRoute
  '/garage-dispatch/services': typeof GarageDispatchServicesRoute
  '/news/$slug': typeof NewsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRoute
  '/gallery': typeof GalleryRoute
  '/garage-dispatch': typeof GarageDispatchRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/garage-dispatch/gallery': typeof GarageDispatchGalleryRoute
  '/garage-dispatch/login': typeof GarageDispatchLoginRoute
  '/garage-dispatch/news': typeof GarageDispatchNewsRoute
  '/garage-dispatch/reviews': typeof GarageDispatchReviewsRoute
  '/garage-dispatch/services': typeof GarageDispatchServicesRoute
  '/news/$slug': typeof NewsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRoute
  '/gallery': typeof GalleryRoute
  '/garage-dispatch': typeof GarageDispatchRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/request': typeof RequestRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/garage-dispatch/gallery': typeof GarageDispatchGalleryRoute
  '/garage-dispatch/login': typeof GarageDispatchLoginRoute
  '/garage-dispatch/news': typeof GarageDispatchNewsRoute
  '/garage-dispatch/reviews': typeof GarageDispatchReviewsRoute
  '/garage-dispatch/services': typeof GarageDispatchServicesRoute
  '/news/$slug': typeof NewsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/drivers'
    | '/gallery'
    | '/garage-dispatch'
    | '/news'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/garage-dispatch/gallery'
    | '/garage-dispatch/login'
    | '/garage-dispatch/news'
    | '/garage-dispatch/reviews'
    | '/garage-dispatch/services'
    | '/news/$slug'
    | '/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/drivers'
    | '/gallery'
    | '/garage-dispatch'
    | '/news'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/garage-dispatch/gallery'
    | '/garage-dispatch/login'
    | '/garage-dispatch/news'
    | '/garage-dispatch/reviews'
    | '/garage-dispatch/services'
    | '/news/$slug'
    | '/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/drivers'
    | '/gallery'
    | '/garage-dispatch'
    | '/news'
    | '/request'
    | '/services'
    | '/sitemap.xml'
    | '/garage-dispatch/gallery'
    | '/garage-dispatch/login'
    | '/garage-dispatch/news'
    | '/garage-dispatch/reviews'
    | '/garage-dispatch/services'
    | '/news/$slug'
    | '/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DriversRoute: typeof DriversRoute
  GalleryRoute: typeof GalleryRoute
  GarageDispatchRoute: typeof GarageDispatchRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  RequestRoute: typeof RequestRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage-dispatch': {
      id: '/garage-dispatch'
      path: '/garage-dispatch'
      fullPath: '/garage-dispatch'
      preLoaderRoute: typeof GarageDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/garage-dispatch/services': {
      id: '/garage-dispatch/services'
      path: '/services'
      fullPath: '/garage-dispatch/services'
      preLoaderRoute: typeof GarageDispatchServicesRouteImport
      parentRoute: typeof GarageDispatchRoute
    }
    '/garage-dispatch/reviews': {
      id: '/garage-dispatch/reviews'
      path: '/reviews'
      fullPath: '/garage-dispatch/reviews'
      preLoaderRoute: typeof GarageDispatchReviewsRouteImport
      parentRoute: typeof GarageDispatchRoute
    }
    '/garage-dispatch/news': {
      id: '/garage-dispatch/news'
      path: '/news'
      fullPath: '/garage-dispatch/news'
      preLoaderRoute: typeof GarageDispatchNewsRouteImport
      parentRoute: typeof GarageDispatchRoute
    }
    '/garage-dispatch/login': {
      id: '/garage-dispatch/login'
      path: '/login'
      fullPath: '/garage-dispatch/login'
      preLoaderRoute: typeof GarageDispatchLoginRouteImport
      parentRoute: typeof GarageDispatchRoute
    }
    '/garage-dispatch/gallery': {
      id: '/garage-dispatch/gallery'
      path: '/gallery'
      fullPath: '/garage-dispatch/gallery'
      preLoaderRoute: typeof GarageDispatchGalleryRouteImport
      parentRoute: typeof GarageDispatchRoute
    }
  }
}

interface GarageDispatchRouteChildren {
  GarageDispatchGalleryRoute: typeof GarageDispatchGalleryRoute
  GarageDispatchLoginRoute: typeof GarageDispatchLoginRoute
  GarageDispatchNewsRoute: typeof GarageDispatchNewsRoute
  GarageDispatchReviewsRoute: typeof GarageDispatchReviewsRoute
  GarageDispatchServicesRoute: typeof GarageDispatchServicesRoute
}

const GarageDispatchRouteChildren: GarageDispatchRouteChildren = {
  GarageDispatchGalleryRoute: GarageDispatchGalleryRoute,
  GarageDispatchLoginRoute: GarageDispatchLoginRoute,
  GarageDispatchNewsRoute: GarageDispatchNewsRoute,
  GarageDispatchReviewsRoute: GarageDispatchReviewsRoute,
  GarageDispatchServicesRoute: GarageDispatchServicesRoute,
}

const GarageDispatchRouteWithChildren = GarageDispatchRoute._addFileChildren(
  GarageDispatchRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DriversRoute: DriversRoute,
  GalleryRoute: GalleryRoute,
  GarageDispatchRoute: GarageDispatchRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  RequestRoute: RequestRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
